export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
  },
  DASHBOARD: {
    HOME: '/dashboard',
    POS: '/pos',
    VENTAS: '/ventas',
    COTIZACIONES: '/cotizaciones',
    PROYECTOS: '/proyectos',
    DEVOLUCIONES: '/devoluciones',
    INVENTARIO: '/inventario',
    CLIENTES: '/clientes',
    CAMPANAS: '/campanas',
    GARANTIAS: '/garantias',
    SERVICIO: '/servicio',
    CAJA: '/caja',
    PEDIDOS: '/pedidos',
    PROVEEDORES: '/proveedores',
    COMPRAS: '/compras',
    DESCUENTOS: '/descuentos',
    CIERRES: '/cierres',
    CONTABILIDAD: '/contabilidad',
    CUENTAS: '/cuentas',
    REPORTES: '/reportes',
    PRESUPUESTO: '/presupuesto',
    FEL: '/fel',
    USUARIOS: '/usuarios',
    ROLES: '/roles',
    SESIONES: '/sesiones',
    CONFIG: '/config',
    AUDITORIA: '/auditoria',
  },
} as const
