// src/app/api/productos/route.ts

import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { ProductoService } from '@/modules/productos/services/producto.service';
import { createProductoSchema, updateProductoSchema } from '@/modules/productos/validators/producto.validator';

export const dynamic = 'force-dynamic';

const service = new ProductoService();

export async function GET(req: NextRequest) {
  try {
    const session = await auth();
    if (!session) return NextResponse.json({ error: 'No autorizado' }, { status: 401 });
    const { searchParams } = new URL(req.url);
    const buscar = searchParams.get('buscar') || '';
    const categoria = searchParams.get('categoria') || '';
    const where: any = { activo: true };
    if (buscar)
      where.OR = [
        { nombre: { contains: buscar, mode: 'insensitive' } },
        { codigo: { contains: buscar, mode: 'insensitive' } },
        { descripcion: { contains: buscar, mode: 'insensitive' } },
      ];
    if (categoria) where.categoriaId = categoria;
    const productos = await service.getAll();
    // Simple filtering matching previous logic
    const filtered = productos.filter((p) => {
      if (!p.activo) return false;
      if (buscar) {
        const term = buscar.toLowerCase();
        return (
          p.nombre.toLowerCase().includes(term) ||
          (p.codigo?.toLowerCase().includes(term) ?? false) ||
          (p.descripcion?.toLowerCase().includes(term) ?? false)
        );
      }
      if (categoria && p.categoria !== categoria) return false;
      return true;
    });
    return NextResponse.json(filtered);
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || 'Error interno' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session) return NextResponse.json({ error: 'No autorizado' }, { status: 401 });
    const body = await req.json();
    const { id } = body;
    const schema = id ? updateProductoSchema : createProductoSchema;
    const parsed = schema.safeParse(body);
    if (!parsed.success) {
      const errorMessage = parsed.error.errors.map(e => e.message).join(', ');
      return NextResponse.json({ error: errorMessage }, { status: 400 });
    }
    let dto = parsed.data as any;
    if (!id) {
      // Ensure required 'codigo' field exists for creation
      if (!dto.codigo) {
        // simple autogenerated code, could be replaced with business logic
        dto.codigo = `PROD-${Date.now()}`;
      }
      const producto = await service.create(dto as any);
      return NextResponse.json({ ok: true, producto });
    } else {
      const producto = await service.update(Number(id), dto);
      return NextResponse.json({ ok: true, producto });
    }
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || 'Error interno' }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  try {
    const session = await auth();
    if (!session || session.user.role !== 'admin')
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 });
    const { searchParams } = new URL(req.url);
    const id = searchParams.get('id');
    if (!id) return NextResponse.json({ error: 'ID requerido' }, { status: 400 });
    await service.delete(Number(id));
    return NextResponse.json({ ok: true });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || 'Error interno' }, { status: 500 });
  }
}
